### ISSUE TITLE
Avoid trim?

### ISSUE THREAD

**Issue by edemaine** [rayrutjes/diffable-html#14]
Calling `text.trim()` on HTML text changes the meaning of HTML content especially when the whitespace in question is not a regular space, but e.g. U+2009 (THIN SPACE).  (Note: `'\u2009'.trim().length == 0`.)  This is essentially a discrepancy from what JavaScript considers whitespace (Unicode definition) from what HTML considers whitespace (tab, LF, FF, space as far as I understand https://www.w3.org/TR/html52/syntax.html).  I just ran into this issue when [generating MathML](https://github.com/KaTeX/KaTeX/pull/1813) in [KaTeX](https://github.com/KaTeX/KaTeX/).

Some options I see:
* Replace `text.trim()` with `text.replace(/^[\t\n\r ]|[\t\n\r ]$/g, '')` or similar more-selective trim.
* Add an option to not run `text.trim()` at all (maybe good to know about differences in spacing?).

Let me know if you'd like a PR in either direction.  Right now we're using [a workaround](https://github.com/KaTeX/KaTeX/pull/1813).

**Comment by rayrutjes** [comment]
I would go for the first option given so far we have a no options.
However I'm open to another approach if you think it makes more sense.

In the end, the intention (I think) was to remove duplicate spaces that added a lot of noise to the diffs. The best would be that we do not alter the HTML content, if you think we can do that I would definitely go with no additional option because as you said, in the end we do want to diff the spaces when they have a meaning.
